### PR TITLE
Event query

### PR DESCRIPTION
**Pull request by artoodeeto**
- made changes on user schema and event schema
- added a sample query to query events with user and user with their events
- **a problem on userTypeDef line 31 where i imported EventType directly**
- change folder structure
- removed console.log
- added controllers for event

### CODE REVIEW

**Comment by artoodeeto** [comment]
@ujwal @cyberputty yow dude heres my changes

**Comment by artoodeeto** [comment]
btw the bug or the problem that i have is on graphql its called **Schema circular dependency issue**

**Review by UjwalBattar — CHANGES_REQUESTED** [review]
conflict resolution

**Review by UjwalBattar — COMMENTED** [review]
do we need to put the events in the user document? I feel like its not necessary since we already have the user id being referenced in the event schema

**Pull request merged**
